In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [34]:
# load dataset
df = pd.read_csv('../datasets/emails.csv')
df.head()

  Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0

[5 rows x 3002 columns]

In [8]:
# dimensions
df.shape

(5172, 3002)

In [9]:
# dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB

In [11]:
# statistical summary
df.describe()

               the           to  ...          dry   Prediction
count  5172.000000  5172.000000  ...  5172.000000  5172.000000
mean      6.640565     6.188128  ...     0.006961     0.290023
std      11.745009     9.534576  ...     0.098086     0.453817
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.000000     1.000000  ...     0.000000     0.000000
50%       3.000000     3.000000  ...     0.000000     0.000000
75%       8.000000     7.000000  ...     0.000000     1.000000
max     210.000000   132.000000  ...     4.000000     1.000000

[8 rows x 3001 columns]

In [13]:
# null values check
df.isnull().sum().sum()

np.int64(0)

In [14]:
df.head()

  Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0

[5 rows x 3002 columns]

In [35]:
# dropping unnecessary features.
df.drop('Email No.', axis=1, inplace=True)

In [36]:
# data preparation
X = df.drop("Prediction", axis=1)
y = df['Prediction']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

In [38]:
# features scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
from sklearn.decomposition import PCA
pca = PCA(n_components=500) # reducing to top 500 components
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [47]:
# getting the classification models
svc = SVC(C=1.0, kernel='rbf', gamma='auto')
knn = KNeighborsClassifier(n_neighbors=7)

In [49]:
# traning the models
svc.fit(X_train, y_train)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [50]:
# prediction
svc_pred = svc.predict(X_test)
knn_pred = knn.predict(X_test)

In [54]:
# getting the results.
result = {
    "SVC": {
        "Accuracy": accuracy_score(y_test, svc_pred),
        "Precision": precision_score(y_test, svc_pred),
        "Recall": recall_score(y_test, svc_pred),
        "F1": f1_score(y_test, svc_pred)
    },
    "KNN": {
        "Accuracy": accuracy_score(y_test, knn_pred),
        "Precision": precision_score(y_test, knn_pred),
        "Recall": recall_score(y_test, knn_pred),
        "F1": f1_score(y_test, knn_pred)
    }
}
result

{'SVC': {'Accuracy': 0.9429951690821256,
  'Precision': 0.9683794466403162,
  'Recall': 0.8277027027027027,
  'F1': 0.8925318761384335},
 'KNN': {'Accuracy': 0.9111111111111111,
  'Precision': 0.7684210526315789,
  'Recall': 0.9864864864864865,
  'F1': 0.863905325443787}}

In [63]:
# confusion matrices
print("Confusion Matrix for SVM")
display(confusion_matrix(y_test, svc_pred))

print("Confusion Matrix for KNN")
display(confusion_matrix(y_test, knn_pred))

Confusion Matrix for SVM

array([[731,   8],
       [ 51, 245]])

Confusion Matrix for KNN

array([[651,  88],
       [  4, 292]])